<a href="https://colab.research.google.com/github/sjohn214/Colab_Predictive2026/blob/main/Page_Shannondale_Week4_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 4 Lab: Conditionals, Loops, Functions, and NumPy

**Course:** ISM 645: Principles of Predictive Analytics  
**Instructor:** Dr. Shimi Zhou  
**Lab:** Week 4

**Name:** Shannondale Page
**Date:** Septemeber 9, 2026

This lab has ten questions. Work top to bottom, complete every `TODO`, and run each cell before moving on. Each question shows the output your code should produce, so you can check your own work as you go.

Questions 1 through 5 review the material at a steady pace. Questions 6 through 8 ask you to manage a little more state on your own. Questions 9 and 10 move into NumPy and are the most demanding part of the lab. All ten are required.


## Learning goals

By the end of this lab you should be able to:

- Combine comparison operators, logical operators, and built-in functions in a single expression
- Choose between `if / elif / else` and a nested `if` based on how the decisions depend on one another
- Iterate over strings, lists, dictionaries, and sets with `for` loops, including nested loops
- Control a `while` loop with an index, a running total, `break`, and `continue`
- Define functions that take parameters and return values, and call them inside a loop
- Create NumPy arrays, slice them, filter them with Boolean and fancy indexing, transpose them, and summarize them


## How to submit

1. Run every cell from the top so that all output is visible.
2. Save the notebook.
3. Rename the file as `LastName_FirstName_Week4_Lab.ipynb`.
4. Upload the `.ipynb` file to the Week 4 Lab assignment in Canvas by Sunday at 11:59 PM.

Solutions are posted the following week, after the submission window closes.


---

## Question 1: Comparison Operators, Logical Operators, and Built-in Functions

*Core*

A store manager wants a quick check on two figures and on a short list of daily order counts. This question reviews the operators and the built-in functions from the first part of the lecture.


**1a.** Using the two variables provided, print the result of three expressions: whether `a` is greater than `b`, whether `a` equals 8 **and** `b` is less than 6, and the negation of `a < b`. Label each printed line so the output is readable.

**Expected output**

```
a > b: True
a == 8 and b < 6: True
not (a < b): True
```


In [90]:
a, b = 8, 5

print(f"a > b: {a >b}") # TODO: print a > b with a label
print(f"a == b: {a == 8 and b < 6}") # TODO: print (a == 8) and (b < 6) with a label
print(f"not (a < b): {not (a < b)}") # TODO: print not (a < b) with a label

a > b: True
a == b: True
not (a < b): True


**1b.** For the list `daily_orders`, print the number of values, the total, the smallest value, the largest value, and the average rounded to two decimal places. Use only the built-in functions `len`, `sum`, `min`, `max`, and `round`.

**Expected output**

```
count: 4 | total: 21 | min: 2 | max: 9 | average: 5.25
```


In [91]:
daily_orders = [3, 7, 2, 9]
order_count = len(daily_orders)
order_total = sum(daily_orders)
order_average = round(order_total / order_count, 2)

order_min = min(daily_orders)
order_max = max(daily_orders)

# TODO: compute the average using sum() and len(), rounded to 2 decimals
print(
    f"Len: {order_count} | Sum: {order_total} | Min: {order_min} | Max: {order_max} | Average: {order_average} "
)
# TODO: print count, total, min, max, and average on one line

Len: 4 | Sum: 21 | Min: 2 | Max: 9 | Average: 5.25 


**1c.** Print the result of `0.1 + 0.2 == 0.3`, then print the value of `0.1 + 0.2` itself, then print a safer comparison that rounds both sides to 10 decimal places before testing equality. In a comment, state which of the three lines you would trust in a data pipeline.

**Expected output**

```
direct comparison: False
stored value: 0.30000000000000004
rounded comparison: True
```


In [92]:
print("Direct comparison:" , 0.1 + 0.2 == 0.3) # TODO: print the direct float comparison
print("Stored value:", 0.1 +0.2) # TODO: print the actual value of 0.1 + 0.2
print("Rounded comparison:", round(0.1 + 0.2, 10)== round(0.3, 10)) # TODO: print the rounded comparison
# TODO: add a comment naming the version you would trust
"Trust the rounded comparison because the floating point has limitations and the stored value input would make exact equality unreliable."

Direct comparison: False
Stored value: 0.30000000000000004
Rounded comparison: True


'Trust the rounded comparison because the floating point has limitations and the stored value input would make exact equality unreliable.'

---

## Question 2: If, Elif, and Else: Discount Tiers and Free Shipping

*Core*

An online store applies a volume discount and a separate free shipping rule to each order. Both rules are decided from a single order total.


**2a.** Assign a discount rate to `order_total` using the following tiers: 20 percent for totals of 100 or more, 10 percent for totals of 60 or more, and 0 percent otherwise. Compute the final price rounded to two decimals, then print the total, the discount rate, and the final price.

**Expected output**

```
Total: 86 | Discount: 0.1 | Final price: 77.4
```


In [93]:
order_total = 86

# TODO: use if / elif / else to set the variable discount
if order_total >= 100:
    discount = 0.20
elif order_total >=60:
  discount = 0.10
else:
  discount = 0.0

# TODO: compute final_price = order_total * (1 - discount), rounded to 2 decimals
final_price = round(order_total * (1 - discount), 2)

# TODO: print order_total, discount, and final_price
print(f"Total: {order_total} | Discount: {discount} | Final price: {final_price}")

Total: 86 | Discount: 0.1 | Final price: 77.4


**2b.** Free shipping applies when the order total reaches 75. Using a single if and else, print `Free Shipping` when the total qualifies and `Standard shipping fee: 5.99` when it does not.

**Expected output**

```
Free Shipping
```


In [94]:
shipping_threshold = 75
order_total = 86

# TODO: if the order qualifies, print Free Shipping
if order_total >= shipping_threshold:
  print("Free Shipping")
# TODO: otherwise print the standard shipping fee
else:
  print("Standard shipping fee: 5.99")

Free Shipping


---

## Question 3: Nested If: Loyalty Membership and Tier

*Core*

Loyalty discounts depend on membership first and on tier second. A tier is meaningless for a customer who is not enrolled, which is the situation the lecture described as a dependent follow-up question.


**3a.** Write a nested if that first checks `is_member`. If the customer is a member, check the tier: Gold receives 20 percent, Silver receives 10 percent, and any other tier receives 5 percent. A non-member receives 0 percent. Print the tier, the discount rate, and the final price rounded to two decimals.

**Expected output**

```
Tier: Gold | Discount: 0.2 | Final price: 192.0
```


In [95]:
is_member = True
tier = 'Gold'
subtotal = 240

# TODO: outer if on is_member
if is_member:
# TODO: inner if / elif / else on tier
  if tier == 'Gold':
    discount = 0.20
  elif tier == 'Silver':
    discount = 0.10
  else:
    discount = 0.05
else:
  tier = 'Non-Member'
  discount = 0.0

final_price = round(subtotal * (1 - discount), 2)

# TODO: print tier, discount, and final price
print(f"Tier: {tier} | Discount: {discount} | Final price: {final_price}")

Tier: Gold | Discount: 0.2 | Final price: 192.0


**3b.** Copy your code from part 3a, change `is_member` to `False`, and run it again to confirm that the tier no longer affects the price.

**Expected output**

```
Tier: Gold | Discount: 0.0 | Final price: 240.0
```


In [96]:
is_member = False
tier = 'Gold'
subtotal = 240

# TODO: paste your nested if here and confirm the discount is 0.00

# TODO: outer if on is_member
if is_member:
    # Inner if / elif / else on tier
    if tier == 'Gold':
        discount = 0.20
    elif tier == 'Silver':
        discount = 0.10
    else:
        discount = 0.05
else:
    tier = 'Non-Member'
    discount = 0.0

final_price = round(subtotal * (1 - discount), 2)

# Print tier, discount, and final price
print(f"Tier: {tier} | Discount: {discount} | Final price: {final_price}")


Tier: Non-Member | Discount: 0.0 | Final price: 240.0


---

## Question 4: For Loops Across Strings, Lists, Dictionaries, and Sets

*Core*

A for loop visits each item in a sequence once. This question runs the same idea across the four data structures covered in the lecture.


**4a.** Print each character of the campaign code on its own line using a for loop.

**Expected output**

```
D
A
T
A
```


In [97]:
campaign = 'DATA'

# TODO: for loop that prints one character per line
for character in campaign:
  print(character)

D
A
T
A


**4b.** Print each region together with its position in the list, formatted as `index 0 -> North`. Use `range(len(regions))` so that the index is available inside the loop.

**Expected output**

```
index 0 -> North
index 1 -> South
index 2 -> East
index 3 -> West
```


In [98]:
regions = ['North', 'South', 'East', 'West']

# TODO: for loop over range(len(regions)) printing index and value
for i in range(len(regions)):
  print(f"index {i} -> {regions[i]}")

index 0 -> North
index 1 -> South
index 2 -> East
index 3 -> West


**4c.** Print one line per region in the form `North sold 120 units`. Use `.items()` so that the key and the value are both available inside the loop.

**Expected output**

```
North sold 120 units
South sold 95 units
East sold 140 units
West sold 160 units
```


In [99]:
units_sold = {'North': 120, 'South': 95, 'East': 140, 'West': 160}

# TODO: for loop using .items() to unpack key and value
for region, units in units_sold.items():
  print(f"{region} sold {units} units")

North sold 120 units
South sold 95 units
East sold 140 units
West sold 160 units


**4d.** Print each marketing channel in the set. In a comment, state what the set removed from the original collection of values.

**Expected output**

```
stored set: {'email', 'search', 'social'}
channel: email
channel: search
channel: social
```

*Your channels may print in a different order. A set does not preserve the order values were typed in, so only the three unique values matter here.*


In [100]:
channels = {'email', 'social', 'search', 'email'}

# TODO: print the set itself
print(f"stored set: {channels}")

# TODO: for loop that prints each channel
for channel in channels:
  print(f" - channel: {channel}")

# TODO: comment on what the set removed
# "Email was deleted because it was a dupicate. Python only stores unique elements so when there is a set, it removes the duplicate."

stored set: {'social', 'search', 'email'}
 - channel: social
 - channel: search
 - channel: email


---

## Question 5: For Loop with If, and Nested For Loops

*Core*

Weekly sales are compared against a target, and a second loop builds every combination of store and product. Both patterns appear constantly in data preparation work.


**5a.** Loop over `weekly_sales` and print `Target met with sales: 140` when a week reaches the target of 120, and `Below target: 95` when it does not.

**Expected output**

```
Below target: 95
Target met with sales: 140
Below target: 110
Target met with sales: 160
Target met with sales: 130
```


In [101]:
weekly_sales = [95, 140, 110, 160, 130]
target = 120

# TODO: for loop with if / else comparing each week to target
for sales in weekly_sales:
  if sales >= target:
    print(f"Target met with sales: {sales}")
  else:
    print(f"Below target: {sales}")


Below target: 95
Target met with sales: 140
Below target: 110
Target met with sales: 160
Target met with sales: 130


**5b.** Count how many weeks met the target and add up the sales from those weeks only. Print the count and the qualifying total. Start both variables at zero before the loop begins.

**Expected output**

```
Weeks that met target: 3
Sales from those weeks: 430
```


In [102]:
weekly_sales = [95, 140, 110, 160, 130]
target = 120

# Create counters before the loop
weeks_met = 0
qualifying_total = 0

# Loop over weekly_sales and update both counters when the target is met
for sales in weekly_sales:
    if sales >= target:
        weeks_met += 1
        qualifying_total += sales

# Print the count and the total
print(f"Weeks meeting target: {weeks_met}")
print(f"Total sales from qualifying weeks: {qualifying_total}")

Weeks meeting target: 3
Total sales from qualifying weeks: 430


**5c.** Use a nested for loop to print every store and product combination, formatted as `Greensboro - Laptop`. The outer loop should move through the stores and the inner loop through the products.

**Expected output**

```
Greensboro - Laptop
Greensboro - Tablet
Greensboro - Phone
Raleigh - Laptop
Raleigh - Tablet
Raleigh - Phone
```


In [103]:
stores = ['Greensboro', 'Raleigh']
products = ['Laptop', 'Tablet', 'Phone']

# TODO: outer loop over stores, inner loop over products
for store in stores:
    for product in products:
      print(f"{store} - {product}")

Greensboro - Laptop
Greensboro - Tablet
Greensboro - Phone
Raleigh - Laptop
Raleigh - Tablet
Raleigh - Phone


---

## Question 6: While Loops with Indexing

*Intermediate*

A while loop repeats as long as its condition stays True. The loop has to change something inside its body, or the condition will never become False.


**6a.** Print each character of `word` on its own line using a while loop and an index variable. Use `len(word)` in the condition.

**Expected output**

```
A
N
A
L
Y
T
I
C
S
```


In [104]:
word = 'ANALYTICS'

# TODO: create an index variable set to 0
index = 0

# TODO: while the index is less than len(word), print the character and move the index forward
while index < len(word):
  print(word[index])
  index += 1

A
N
A
L
Y
T
I
C
S


**6b.** Use a while loop to walk through `daily_orders`, adding each value to a running total and printing the running total after each day.

**Expected output**

```
Running total: 12
Running total: 31
Running total: 38
Running total: 61
Running total: 76
```


In [105]:
# @title
daily_orders = [12, 19, 7, 23, 15]

# TODO: create total = 0 and i = 0
total = 0
i = 0

# TODO: while loop that adds daily_orders[i] to total and prints the running total
while i < len(daily_orders):
  total += daily_orders[i]
  print(f"Running total: {total}")
  i += 1

Running total: 12
Running total: 31
Running total: 38
Running total: 61
Running total: 76


**6c.** Stop early once the running total reaches 50. Use a condition that checks both the total and the index, then print how many days were needed.

**Expected output**

```
Days needed: 4 | Total reached: 61
```


In [106]:
# TODO: reset total and i to 0
total = 0
i = 0

# TODO: while total < 50 and i < len(daily_orders): accumulate and advance
while total < 50 and i < len(daily_orders):
  total += daily_orders[i]
  i += 1
# TODO: print the number of days needed and the final total
print(f"Days needed: {i} | Total reached: {total}")

Days needed: 4 | Total reached: 61


---

## Question 7: Break and Continue

*Intermediate*

`break` leaves the loop immediately and `continue` skips the rest of the current pass. Both are tested inside a loop with an if statement.


**7a.** Write a while loop over the numbers 0 through 9 that skips the value 5 using `continue` and stops entirely at the value 8 using `break`. Print the values that survive, separated by spaces.

**Expected output**

```
0 1 2 3 4 6 7
```


In [107]:
n = 0

# TODO: while n < 10, skip 5 with continue and stop at 8 with break
while n < 10:
    if n == 5:
        n += 1
        continue
    if n == 8:
        break

# TODO: print the surviving values on one line using print(n, end=' ')
    print(n, end=' ')
    n += 1

0 1 2 3 4 6 7 

**7b.** Review the transactions in order. Skip any transaction of 0 with `continue`, and when a transaction above 200 is found, print `Flagged for review: 210` and stop the loop with `break`. Print each transaction that is checked and passes.

**Expected output**

```
Checked: 45
Checked: 80
Checked: 30
Flagged for review: 210
```


In [108]:
transactions = [45, 0, 80, 30, 210, 60]

# TODO: for loop with continue for zero values and break for values above 200
for transaction in transactions:
  if transaction == 0:
    continue
  if transaction > 200:
    print(f"Flagged for review: {transaction}")
    break
  print(f"Checked: {transaction}")

Checked: 45
Checked: 80
Checked: 30
Flagged for review: 210


---

## Question 8: User-Defined Functions

*Intermediate*

A function packages a block of statements under a name so it can be called repeatedly with different inputs. Each function here takes parameters and returns a value rather than printing inside the function body.


**8a.** Define a function `greet_customer(name)` that returns a greeting string such as `Hello, Avery!`. Call it twice with different names and print each result.

**Expected output**

```
Hello, Avery!
Hello, Jordan!
```


In [109]:
# TODO: def greet_customer(name): return a greeting string
def greet_customer(name):
  return f"Hello, {name}!"
# TODO: print the result of two calls
print(greet_customer("Avery"))
print(greet_customer("Jordan"))

Hello, Avery!
Hello, Jordan!


**8b.** Define a function `classify_order(total)` that returns `large` for totals of 200 or more, `medium` for totals of 75 or more, and `small` otherwise. Test it on the values 320, 90, and 40.

**Expected output**

```
large medium small
```


In [110]:
# TODO: def classify_order(total) using if / elif / else and return
def classify_order(total):
  if total >= 200:
    return "large"
  elif total >= 75:
    return "medium"
  else:
    return "small"
# TODO: print the classification for 320, 90, and 40
print(classify_order(320), classify_order(90), classify_order(40))

large medium small


**8c.** Define a function `average_sales(values)` that returns the average of a list rounded to two decimals. Then loop over `order_totals`, print each total together with its label from `classify_order`, and print the average of the list at the end.

**Expected output**

```
320 is a large order
90 is a medium order
40 is a small order
150 is a medium order
210 is a large order
Average order total: 162.0
```


In [111]:
# TODO: def average_sales(values) returning the rounded average
def classify_order(total):
  if total >= 200:
    return "is a large order"
  elif total >= 75:
    return "is a medium order"
  else:
    return "is a small order"
# TODO: for loop printing each total and its classification
def average_sales(values):
  if not values:
    return 0.0
  return round(sum(values) / len(values), 2)

order_totals = [320, 90, 40, 150, 210]

for total in order_totals:
  classification = classify_order(total)
  print(f"{total} -> {classification}")

# TODO: print the average
avg = average_sales(order_totals)
print(f"Average order total: {avg}")

320 -> is a large order
90 -> is a medium order
40 -> is a small order
150 -> is a medium order
210 -> is a large order
Average order total: 162.0


---

## Question 9: NumPy Arrays: Creation, Attributes, Slicing, and Element-wise Math

*Advanced*

NumPy stores numbers in an ndarray, which applies an operation to every element at once. This question builds arrays, inspects them, and pulls pieces out with slicing.


**9a.** Import NumPy under the alias `np`, build a one-dimensional array from the list `[10, 20, 30, 40]`, and print its `dtype`, `shape`, and `ndim`. Then print the array multiplied by 2, and print the plain Python list multiplied by 2. In a comment, describe the difference.

**Expected output**

```
dtype: int64 | shape: (4,) | ndim: 1
array * 2: [20 40 60 80]
list * 2: [10, 20, 30, 40, 10, 20, 30, 40]
```

*Some older installations on Windows report the dtype as int32 rather than int64. Either result is correct.*


In [112]:
import numpy as np

price_list = [10, 20, 30, 40]

# TODO: create prices as a NumPy array from price_list
prices = np.array(price_list)

# TODO: print dtype, shape, and ndim
print(f"dtype: {prices.dtype} | shape: {prices.shape} | ndim: {prices.ndim}")

# TODO: print prices * 2 and price_list * 2
print(f"array * 2: {prices * 2}")
print(f"list * 2: {price_list * 2}")
# TODO: comment on the difference
# "When multiplying and array by 2, we double the number inside the array"
# "By multiplying a list by 2, we repeat the sequence, concatenating the list within itself"

dtype: int64 | shape: (4,) | ndim: 1
array * 2: [20 40 60 80]
list * 2: [10, 20, 30, 40, 10, 20, 30, 40]


**9b.** Create and print four arrays using the constructors from the lecture: a 2 by 3 array of zeros, a 2 by 2 array filled with the value 7, the even numbers from 0 up to but not including 10, and five evenly spaced values between 0 and 1.

**Expected output**

```
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
full:
 [[7 7]
 [7 7]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
```


In [113]:
import numpy as np

# TODO: np.zeros with shape (2, 3)
zeros_arr = np.zeros((2, 3))
print("zeros:")
print(zeros_arr)

# TODO: np.full with shape (2, 2) and value 7
full_arr = np.full((2, 2), 7)
print("\nfull:")
print(full_arr)

# TODO: np.arange from 0 to 10 with step 2
arange_arr = np.arange(0, 10, 2)
print(f"arange: {arange_arr}")

# TODO: np.linspace from 0 to 1 with 5 values
linspace_arr = np.linspace(0, 1, 5)
print(f"linspace: {linspace_arr}")

zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

full:
[[7 7]
 [7 7]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


**9c.** Build a 3 by 4 array from `np.arange(12)` using `.reshape()`. Print the whole array, the first row, the last column, and the block made of the first two rows and columns 1 through 2.

**Expected output**

```
grid:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first row: [0 1 2 3]
last column: [ 3  7 11]
rows 0 to 1, columns 1 to 2:
 [[1 2]
 [5 6]]
```


In [114]:
import numpy as np

# TODO: create grid with np.arange(12).reshape(3, 4)
grid = np.arange(12).reshape(3, 4)
# TODO: print the array, grid[0, :], grid[:, -1], and grid[0:2, 1:3]
print(f"grid: {grid}")
print(f"first row: {grid[0, :]}")
print(f"last column: {grid[:, -1]}")
print(f"rows 0 to 1, columns 1 to 2: {grid[0:2, 1:3]}")

grid: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first row: [0 1 2 3]
last column: [ 3  7 11]
rows 0 to 1, columns 1 to 2: [[1 2]
 [5 6]]


**9d.** Apply a 10 percent discount to `catalog_prices` with one expression, print the discounted array, and print the amount saved on each item.

**Expected output**

```
discounted: [ 90. 225. 270. 135.]
savings: [10. 25. 30. 15.]
```


In [115]:
import numpy as np
catalog_prices = np.array([100, 250, 300, 150])

# TODO: compute and print the discounted prices
discounted_prices = catalog_prices * 0.90
print(f"discounted: {discounted_prices}")

# TODO: compute and print the savings per item
savings = catalog_prices * 0.10
print(f"savings: {savings}")

discounted: [ 90. 225. 270. 135.]
savings: [10. 25. 30. 15.]


---

## Question 10: NumPy Selection, Transpose, and Summary Statistics

*Advanced*

The array below holds quarterly sales for three stores across four quarters. Each row is a store and each column is a quarter. This question filters it, rearranges it, and summarizes it.


**10a.** Create a Boolean mask that is True where quarterly sales are above 150. Print the mask, print only the values above 150, print how many values that is, and print the proportion of all values that clear the threshold.

**Expected output**

```
mask:
 [[False False False  True]
 [ True  True  True  True]
 [False False False False]]
values above 150: [160 210 180 175 205]
count above 150: 5
proportion above 150: 0.4166666666666667
```


In [116]:
import numpy as np

quarterly = np.array([[120,  95, 140, 160],
                      [210, 180, 175, 205],
                      [ 90, 130, 115, 150]])

# TODO: build the mask quarterly > 150 and print it
mask = quarterly > 150
print("mask:")
print(mask)
# TODO: print the values selected by the mask
print(f"\nvalues above 150: {quarterly[mask]}")
# TODO: print the count and the proportion using .sum() and .mean()
print(f"count above 150: {mask.sum()}")
print(f"proportion above 150: {mask.mean()}")


mask:
[[False False False  True]
 [ True  True  True  True]
 [False False False False]]

values above 150: [160 210 180 175 205]
count above 150: 5
proportion above 150: 0.4166666666666667


**10b.** Use fancy indexing to pull out the first and third stores, and from those two rows keep only the second and fourth quarters. Print the resulting block.

**Expected output**

```
stores 1 and 3, quarters 2 and 4:
 [[ 95 160]
 [130 150]]
```


In [117]:
import numpy as np

quarterly = np.array([[120,  95, 140, 160],
                      [210, 180, 175, 205],
                      [ 90, 130, 115, 150]])

# TODO: select rows 0 and 2, then columns 1 and 3
block = quarterly[np.ix_([0, 2], [1, 3])]

# TODO: print the result
print("stores 1 and 3, quarters 2 and 4:")
print(block)

stores 1 and 3, quarters 2 and 4:
[[ 95 160]
 [130 150]]


**10c.** Print the shape of `quarterly`, then print the transposed array and its shape. Confirm that `np.swapaxes(quarterly, 0, 1)` produces the same shape as `.T`.

**Expected output**

```
original shape: (3, 4)
transposed:
 [[120 210  90]
 [ 95 180 130]
 [140 175 115]
 [160 205 150]]
transposed shape: (4, 3)
swapaxes shape: (4, 3)
```


In [118]:
import numpy as np

quarterly = np.array([[120,  95, 140, 160],
                      [210, 180, 175, 205],
                      [ 90, 130, 115, 150]])

# TODO: print the original shape
print(f"original shape: {quarterly.shape}")

# TODO: print quarterly.T and its shape
transposed = quarterly.T
print(f"transposed:")
print(transposed)
print(f"transposed shape: {transposed.shape}")

# TODO: print the shape from np.swapaxes(quarterly, 0, 1)
swapped_shape = np.swapaxes(quarterly, 0, 1).shape
print(f"swapaxes shape: {swapped_shape}")

original shape: (3, 4)
transposed:
[[120 210  90]
 [ 95 180 130]
 [140 175 115]
 [160 205 150]]
transposed shape: (4, 3)
swapaxes shape: (4, 3)


**10d.** Print the total of all sales, the mean of each quarter across stores, the maximum for each store, and the index of the store with the highest total. Use `axis=0` for column summaries and `axis=1` for row summaries.

**Expected output**

```
total sales: 1770
mean per quarter: [140.         135.         143.33333333 171.66666667]
max per store: [160 210 150]
store totals: [515 770 485]
strongest store index: 1
```


In [119]:
import numpy as np

quarterly = np.array([[120,  95, 140, 160],
                      [210, 180, 175, 205],
                      [ 90, 130, 115, 150]])

# TODO: total across the whole array
total_sales = quarterly.sum()

# TODO: mean per quarter with axis=0
quarter_means = quarterly.mean(axis=0)

# TODO: max per store with axis=1
store_maxes = quarterly.max(axis=1)

# TODO: totals per store, then argmax to find the strongest store
store_totals = quarterly.sum(axis=1)
strongest_store_index = store_totals.argmax()

#output results
print(f"total sales: {total_sales}")
print(f"mean per quarter: {quarter_means}")
print(f"max per store: {store_maxes}")
print(f"store totals: {store_totals}")
print(f"strongest store index: {strongest_store_index}")

total sales: 1770
mean per quarter: [140.         135.         143.33333333 171.66666667]
max per store: [160 210 150]
store totals: [515 770 485]
strongest store index: 1


---

## Before you submit

- Every `TODO` has been replaced with working code
- The notebook runs from top to bottom without errors after `Kernel > Restart & Run All`
- Your output matches the expected output shown under each question
- Your name is filled in at the top of the notebook
